config/routes.rb
Rails.application.routes.draw do

  get '/' => 'pages#home', as: :root
  get '/about' => 'pages#about'
  get '/gallery' => 'pictures#index'
  get '/gallery/:id' => 'pictures#show', as: :picture
  get '/menu' => 'menu_categories#index'
  get '/happyhour' => 'pages#happy'
  match '/contacts',     to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]
  get "*missing" => redirect("/")

end

app/models/category_item.rb
class Category_item < ActiveRecord::Base
	belongs_to :menu_category
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact from San Telmo Website",
      :to => "santelmoflores@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/menu_category.rb
class Menu_category < ActiveRecord::Base
	has_many :category_items
end

app/models/picture.rb
class Picture < ActiveRecord::Base

	def prev
		Picture.where("id < ?", id).last
	end

	def next
		Picture.where("id > ?", id).first
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
    	@contact = Contact.new
 	end

  	def create
    	@contact = Contact.new(params[:contact])
    	@contact.request = request
    	if @contact.deliver
      		flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    	else
      		flash.now[:error] = 'Cannot send message.'
      		render :new
    	end
  	end
end

app/controllers/menu_categories_controller.rb
class MenuCategoriesController < ApplicationController
	def index
		@menu_categories = Menu_category.all
		@category_items = Category_item.all
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def about
	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	def index
		@pictures = Picture.all
	end

	def show
		@picture = Picture.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/menu_categories_helper.rb
module MenuCategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/contacts/create.html.erb
<div class="create" id="create">
	<div class="container">
	<div class="app-nav">
			<%= link_to :back do %>
				<i class="material-icons">chevron_left</i>
			<% end %>
		</div>
  <% flash.each do |key, value| %>
    <div>
       <h1> <%= value %></h1>
    </div>
  <% end %>
</div>
</div>

app/views/contacts/new.html.erb
<div class="jumbotron" id="contact">
  <h1>Contact Us</h1>
</div>
<div class="contact">
  <div class="row">
    <div class="col-md-5 col-xs-12" id="form">
      <h1>Send Us a Message</h1>

      <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
      <%= f.input :name, :required => true %>
      <%= f.input :email, :required => true %>
      <%= f.input :message, :as => :text, :required => true %>
      <div class= "hidden">
        <%= f.input :nickname, :hint => 'Leave this field blank!' %>
      </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
    </div>
    <div class="col-md-7 col-xs-12" >
      <img class="img-responsive" src="/images/SAM_2422.jpg">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	  <!--bootstrap-->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
		<link rel="icon" href="/images/logo-low.ico">
  <title>Restaurante San Telmo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
		<!--font-->
		<link href='https://fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>
		<!--mobile friendly-->
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <!--font awesome-->
  		<script src="https://use.fontawesome.com/811422e9bc.js"></script>
    	<!--material icons-->
    	<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
</head>
<body id="bs-over">
	<div id="top">
	</div>
	<!--for mobile-->
		<div class="icon-menu pull-left">
  			<i class="material-icons">&#xE5D2;</i>
  		</div>
	 <!-- Mobile Menu -->
		<div class="menu">
			<div class="row">
			<div class="col-md-12 col-xs-12">
			<div class="icon-close">
				<i class="material-icons">&#xE5CD;</i>
			</div>
			<ul>
			 	<li><a href="/menu">Menu</a></li>
				<li><a href="/gallery">Gallery</a></li>
				<li><a href="/about">About</a></li>
				<li><a href="/contacts">Contact Us</a></li>
			</ul>
		</div>
	</div>
</div>
	<!--header-->
			<div class="header">
				<div class="container">
						<a href="/"><img class="mobile-logo" src="/images/Logo-low.png" height="150px"/></a>

						  <!--desktop nav-->
						<ul class="nav">
							<li><a href="/menu">Menu</a></li>
							<li><a href="/gallery">Gallery</a></li>
							<li><a href="/"><img src="/images/Logo-low.png" height="150px"/></a></li>
							<li><a href="/about">About</a></li>
							<li><a href="/contacts">Contact Us</a></li>
						</ul>
					</div>
				</div>
				 <!--email icon-->
    			<div class="email-button">
      				<div class="container">
      					<a href="/contacts"><i class="material-icons md-36" id="location">&#xE0BE;</i></a>
      				</div>
    			</div>
<%= yield %>

<!--footer-->
		<div class="footer">
			<ul id="up">
				<li><a href="#top"><i class="material-icons">&#xE316;</i></a></li>
			</ul>
			<div class="container">
				<div class="row">
					<div class="col-md-4 col-xs-4">
						<h3>Location</h3>
						<p>Calle La Union, Isla de Flores, Peten, Guatemala</p>
					</div>
					<div class="col-md-4 col-xs-4">
						<h3>Opening Hours</h3>
						<p>Monday-Sunday <br> 7 a.m.-11 p.m.</p>
					</div>
					<div class="col-md-4 col-xs-4">
						<h3>Follow Us</h3>
						<ul>
							<li><a href="https://www.facebook.com/SanTelmoflores/" target="_blank"><i class="fa fa-facebook fa-2x" aria-hidden="true"></i>
</a></li>
							<li><a href="https://www.instagram.com/san_telmo_flores/" target="_blank"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i>
</a></li>
							<li><a href="https://www.tripadvisor.com/Restaurant_Review-g562625-d4071525-Reviews-San_Telmo_Restaurant-Flores_Peten_Department.html" target="_blank"><i class="fa fa-tripadvisor fa-2x" aria-hidden="true"></i>
</a></li>
						</ul>
					</div>
				</div>
				<div id="TA_cdsratingsonlynarrow817" class="TA_cdsratingsonlynarrow"><ul id="CaFDukb" class="TA_links oyDYs0eNIAd"><li id="hSClY5eNJ" class="JSxGBoLPdgo"><a target="_blank" href="https://www.tripadvisor.com/"><img src="https://www.tripadvisor.com/img/cdsi/img2/branding/tripadvisor_logo_transp_340x80-18034-2.png" alt="TripAdvisor"/></a></li></ul></div><script src="https://www.jscache.com/wejs?wtype=cdsratingsonlynarrow&amp;uniq=817&amp;locationId=4071525&amp;lang=en_US&amp;border=true&amp;shadow=true&amp;backgroundColor=white&amp;display_version=2"></script>
			</div>
		</div>

		<!-- Latest compiled and minified JavaScript for bootstrap -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
		<script type="text/javascript">
			var main = function() {	
 		 /* Push the body and the nav over by 280px over */
 		 	$('.icon-menu').click(function() {
    		$('.menu').animate({
      		left: "0px"
    		}, 200);

    		$('body').animate({
      		left: "280px"
    		}, 200);
  			});

  		/* Then push them back */
  			$('.icon-close').click(function() {
    		$('.menu').animate({
      		left: "-280px"
    		}, 200);

    		$('body').animate({
      		left: "0px"
    		}, 200);
  			});
			};

			$(document).ready(main);
		</script>
</body>
</html>

app/views/menu_categories/index.html.erb
<div class="rest-menu">
<!--jumbotron-->
		<div class="jumbotron" id="rest-menu">
				<div class="container">
					<h1>Menu</h1>
				</div>
			</div>
	<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="10000">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
    <li data-target="#myCarousel" data-slide-to="5"></li>
    <li data-target="#myCarousel" data-slide-to="6"></li>
    <li data-target="#myCarousel" data-slide-to="7"></li>
    <li data-target="#myCarousel" data-slide-to="8"></li>
    <li data-target="#myCarousel" data-slide-to="9"></li>
    <li data-target="#myCarousel" data-slide-to="10"></li>
    <li data-target="#myCarousel" data-slide-to="11"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="/menu/menu.jpg" alt="Chania">
    </div>

    <div class="item">
      <img src="/menu/menu-2.jpg" alt="Chania">
    </div>

    <div class="item">
      <img src="/menu/menu-3.jpg" alt="Flower">
    </div>

    <div class="item">
      <img src="/menu/menu-5.jpg" alt="Flower">
    </div>

    <div class="item">
      <img src="/menu/menu-6.jpg" alt="Flower">
    </div>

    <div class="item">
      <img src="/menu/menu-7.jpg" alt="Flower">
    </div>

    <div class="item">
      <img src="/menu/menu-8.jpg" alt="Flower">
    </div>

    <div class="item">
      <img src="/menu/menu-9.jpg" alt="Flower">
    </div>

    <div class="item">
      <img src="/menu/menu-10.jpg" alt="Flower">
    </div>

    <div class="item">
      <img src="/menu/menu-11.jpg" alt="Flower">
    </div>

    <div class="item">
      <img src="/menu/menu-12.jpg" alt="Flower">
    </div>

    <div class="item">
      <img src="/menu/menu-6.jpg" alt="Flower">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/pages/about.html.erb
<div class="about">
<!--jumbotron-->
		<div class="jumbotron" id="about">
			<div class="container">
				<h1>About Us</h1>
			</div>
		</div>
		<!--supporting-->
		<div class="supporting">
			<div class="container">
				<div class="row" id="our-menu">
					<div class="col-md-5">
						
					</div>
					<div class="col-md-7">
						<h1>Our Menu</h1>
						<p>The Menu at San Telmo was carefully made by the Chef and Owner Silvana. She began her cuisine studies in Cordova, Argentina and then traveled around the world picking the best flavors and combinations possible to give   her menu the best food in the area. San Telmo has a huge variety of food and drinks that will make it hard to make a choice. We have carnivore, vegetarian and vegan options to make everyone feel confortable. Please don't forget to give yourself a little pleasure with our delicious homemade desserts.</p>
				</div>
			</div>
			<div class="row" id="our-antiques">
				<div class="col-md-7">
					<h1>Our Antiques</h1>
					<p>San Telmo is full of antiques collected all around the world. We believe every piece of antique has it's own energy and is part of what makes the site unique and with soul. </p>
				</div>
				<div class="col-md-5">
				</div>
			</div>
			<div class="row" id="our-inspiration">
				<div class="col-md-5">
				
				</div>
				<div class="col-md-7">
					<h1>Our Inspiration</h1>
					<p>We get inspired by nature and it's perfect imperfection. The symmetric and asymmetric shapes founded in nature fill our heart with excitement, and our minds with beautiful ideas. </p>
				</div>
			</div>
			<div class="row" id="our-friends">
				<div class="col-md-7">
					<h1>Our Friends</h1>
					<p>Yes, our clients are our beloved friends. We work hard, and with tons of love everyday to improve our site, to re invent ourself, to evolve in order to give our friends a great, new, fresh experience.</p>
				</div>
				<div class="col-md-5">
					
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pages/happy.html.erb
<div class="happy">
		<div class="jumbotron">
			<h1>Happy Hour</h1>
			<h3>From 5 - 9 p.m. everyday </h3>
	</div>
</div>

app/views/pages/home.html.erb
<!--jumbotron-->
		<div class="jumbotron" id="home">
		</div>

<!--supporting-->
		<div class="supporting" id="supporting-home">
			<h1>Food Like Home!</h1>
			<p> Try all our plates before you leave.</p>
			<a class="btn btn-default" href="/menu" role="button">View Our Menu</a>
		</div>
		<!--feature-->
		<div class="feature-1">
			<div class="container">
			<h1>Bookings.</h1>
			<p>Make a table reservation. </p>
			<a class="btn btn-default" id="book-now" href="/contacts">Book Now</a>
		</div>
		</div>
		<div class="feature-2">
			<div class="container">
			<h1>Healthy Food.</h1>
			<p> A healthy outside starts from the inside! </p>
			<a class="btn btn-default" id="hotel-btn" href="/menu" role="button">View Our Menu</a>
		</div>
		</div>
		<div class="feature-3">
			<div class="container">
			<h1>Food With a View.</h1>
			<p>Enjoy the best view in Isla de Flores.</p>
			<a class="btn btn-default" id="hotel-btn" href="/gallery" role="button">View Our Gallery</a>
		</div>
		</div>

app/views/pages/hotel.html.erb
<div class="hotel">
	<div class="jumbotron">
		<h1>Hotel<H1>
	</div>
	<div class="feature">
		<h1>Free Wi-fi</h1>
	</div>
	<div class="feature-2">
		<h1>Lake View</h1>
	</div>
	<div class="feature-3">
		<h1>A/C & Private Bathroom</h1>
	</div>
  <!-- Carousel -->
	<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="10000">
  <!-- Indicators -->
  	<ol class="carousel-indicators">
    	<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    	<li data-target="#myCarousel" data-slide-to="1"></li>
    	<li data-target="#myCarousel" data-slide-to="2"></li>
    	<li data-target="#myCarousel" data-slide-to="3"></li>
    	<li data-target="#myCarousel" data-slide-to="4"></li>
    </ol>
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="/images/SAM_2003.jpg" alt="Mandala">
    </div>

    <div class="item">
      <img src="/images/SAM_2006.jpg" alt="Deck">
    </div>

    <div class="item">
      <img src="/images/SAM_2021.jpg" alt="Chill">
    </div>

    <div class="item">
      <img src="/images/SAM_2150.jpg" alt="A/C">
    </div>

    <div class="item">
      <img src="/images/SAM_2165.jpg" alt="Flower">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
 </div>
</div>

app/views/pictures/index.html.erb
<div class="jumbotron" id ="gallery">
	<h1>Gallery</h1>
</div>
<!--gallery-->
<div class="galleria">
	<div class="container">
		<h4>Photography by <a href="https://alixgaldin.wordpress.com" target="_blank">Alice Galdwin</a></h4>
		<div class="row">
		<% @pictures.each do |p| %>
			<div class="col-md-4 col-xs-12" >
				<%= link_to picture_path(p) do %>
					<img src="<%= p.url %>"/>
				<% end %>
			</div>
		<% end %>
		</div>
	</div>
</div>

app/views/pictures/show.html.erb
<div class="photograph">
	<div class="container">
		<div class="app-nav">
			<%= link_to "/gallery" do %>
				<i class="material-icons">chevron_left</i>
			<% end %>
		</div>
		<div class="photo row">
			<div class="col-md-10 col-md-offset-1 col-xs-12" id="photo">
				<img class="img-responsive" src="<%= @picture.url %>" >
				<h2><%= @picture.name %></h2>
				<p>
				<%= link_to " Next Picture >", @picture.next, :class => "pull-right" %> 
				<%= link_to "< Previous Picture", @picture.prev, :class => "pull-right" %>
				</p>
			</div>
		</div>
	</div>
</div>